In [1]:
%run E:\IITD\Depression-IITD\common.ipynb
%run E:\IITD\Depression-IITD\preprocessing.ipynb

Creating RawArray with float64 data, n_channels=32, n_times=74999
    Range : 0 ... 74998 =      0.000 ...   149.996 secs
Ready.


## LOAD DATA

In [2]:
# # PRE VS CONTROL
# raw_MDD = mne.io.read_raw_fif("loadData/rawMDDpre5.fif")
# raw_control = mne.io.read_raw_fif("loadData/rawControlOnline104.fif")

# epochs_MDD = mne.read_epochs("loadData/epochsMDDpre5.fif", preload=False)
# epochs_control = mne.read_epochs("loadData/epochsControlOnline104.fif", preload=False)

In [3]:
# PRE VS POST
raw_MDD = mne.io.read_raw_fif("loadData/rawMDDpre5.fif")
raw_control = mne.io.read_raw_fif("loadData/rawMDDpost5.fif")

epochs_MDD = mne.read_epochs("loadData/epochsMDDpre5.fif", preload=False)
epochs_control = mne.read_epochs("loadData/epochsMDDpost5.fif", preload=False)


Opening raw data file loadData/rawMDDpre5.fif...
    Read a total of 1 projection items:
        Average EEG reference (1 x 32) active
    Range : 0 ... 74998 =      0.000 ...   149.996 secs
Ready.


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\2280852796.py:2: RuntimeWarning: This filename (loadData/rawMDDpre5.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw_MDD = mne.io.read_raw_fif("loadData/rawMDDpre5.fif")


Opening raw data file loadData/rawMDDpost5.fif...
    Read a total of 1 projection items:
        Average EEG reference (1 x 32) active
    Range : 0 ... 74998 =      0.000 ...   149.996 secs
Ready.
Reading e:\IITD\Depression-IITD\loadData\epochsMDDpre5.fif ...
    Read a total of 1 projection items:
        Average EEG reference (1 x 32) active
    Found the data of interest:
        t =       0.00 ...    4000.00 ms
        0 CTF compensation matrices available
Not setting metadata
73 matching events found
No baseline correction applied
Created an SSP operator (subspace dimension = 1)
1 projection items activated
Reading e:\IITD\Depression-IITD\loadData\epochsMDDpost5.fif ...
    Read a total of 1 projection items:
        Average EEG reference (1 x 32) active
    Found the data of interest:
        t =       0.00 ...    4000.00 ms
        0 CTF compensation matrices available
Not setting metadata
72 matching events found
No baseline correction applied
Created an SSP operator (subspac

C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\2280852796.py:3: RuntimeWarning: This filename (loadData/rawMDDpost5.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw_control = mne.io.read_raw_fif("loadData/rawMDDpost5.fif")
C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\2280852796.py:5: RuntimeWarning: This filename (loadData/epochsMDDpre5.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs_MDD = mne.read_epochs("loadData/epochsMDDpre5.fif", preload=False)
C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\2280852796.py:6: RuntimeWarning: This filename (loadData/epochsMDDpost5.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs

In [ ]:
# # POST vs Control
# raw_MDD = mne.io.read_raw_fif("loadData/rawMDDpost5.fif")
# raw_control = mne.io.read_raw_fif("loadData/rawControlOnline104.fif")

# epochs_MDD = mne.read_epochs("loadData/epochsMDDpost5.fif", preload=False)
# epochs_control = mne.read_epochs("loadData/epochsControlOnline104.fif", preload=False)

In [37]:
def calculate_avergae_components(G):
    connected_components = list(nx.connected_components(G))
    component_avg_lengths = []
    component_nbc_values = []
    component_eglo_values = []
    component_cc_values = []
    component_eloc_values = []

    for component in connected_components:
        subgraph = G.subgraph(component)
        component_avg_lengths.append(nx.average_shortest_path_length(subgraph))
        component_nbc_values.append(nx.betweenness_centrality(subgraph))
        component_eglo_values.append(nx.global_efficiency(subgraph))
        component_cc_values.append(nx.average_clustering(subgraph))
        component_eloc_values.append(nx.local_efficiency(subgraph))

    merged_nbc_values = {}
    for dnbc in component_nbc_values:
        merged_nbc_values.update(dnbc)
    merged_nbc_values = dict(sorted(merged_nbc_values.items(), key=lambda item: item[0]))
    # merged_cc_values = {}
    # for dcc in component_cc_values:
    #     merged_cc_values.update(dcc)
    # merged_cc_values = dict(sorted(merged_cc_values.items(), key=lambda item: item[0]))

    overall_avg_length = sum(component_avg_lengths) / len(component_avg_lengths)
    overall_eglo_values = sum(component_eglo_values) / len(component_eglo_values)
    overall_cc_values = sum(component_cc_values) / len(component_cc_values)
    overall_eloc_values = sum(component_eloc_values) / len(component_eloc_values)

    return [overall_avg_length, merged_nbc_values, overall_eglo_values, overall_cc_values, overall_eloc_values]

# ELSE COMPUTE DATA

MDD data

In [ ]:
# eye_close_MDD = []
eye_close_1 = '\\Depression-Sample-dataset-AIIMS\\Active\\PreetiSingh\\pre\\' + '20230718201550_Preeti singh_22.08.23-01_Eye Close'
eye_close_2 = '\\Depression-Sample-dataset-AIIMS\\Active\\Hemlata\\pre\\' + '20230831105330_Hemlata_05.10.23_01_Eye Close'
eye_close_3 = '\\Depression-Sample-dataset-AIIMS\\Active\\VinodKumarSharma\\pre\\' + '20230829195416_VinodKumarSharma_25.9.23_01_Eye Close'
eye_close_4 = '\\Depression-Sample-dataset-AIIMS\\Sham\\JitenderKumar\\pre\\' + '20230825020227_JitenderKumar_29.08.23_01_Eye Close'
eye_close_5 = '\\Depression-Sample-dataset-AIIMS\\Sham\\SeemaKumari\\pre\\' + '20230827073914_SeemaKumari_11.09.23_01_Eye Close'
# eye_close_6 = '\\Depression-Sample-dataset-AIIMS\\Active\\PreetiSingh\\post\\' + '20230826225729_PreetiSingh_08.09.23_20_Eye Close'
# eye_close_7 = '\\Depression-Sample-dataset-AIIMS\\Active\\Hemlata\\post\\' + '20231019110530_Hemlata_19.10.23_19A_Eye Close'
# eye_close_8 = '\\Depression-Sample-dataset-AIIMS\\Active\\VinodKumarSharma\\post\\' + '20230901112451_VinodKumarSharma_11.10.23_20_Eye Close'
# eye_close_9 = '\\Depression-Sample-dataset-AIIMS\\Sham\\JitenderKumar\\post\\' + '20230827174115_JitenderKumar_13.09.23_20_Eye Close'
# eye_close_10 = '\\Depression-Sample-dataset-AIIMS\\Sham\\SeemaKumari\\post\\' + '20230829172634_SeemaKumari_23.9.23_20_Eye Close'
eye_close_MDD = [eye_close_1, eye_close_2, eye_close_3, eye_close_4, eye_close_5]

In [ ]:
raw_MDD = []
# folder_path = os.getcwd()+'\\Depression-Sample-dataset-AIIMS\\'
for file in eye_close_MDD:
    file_path = os.getcwd()+ eye_close_MDD[i] + '.easy'
    raw = data_transformation_easy(file_path)
    # raw = mne.io.read_raw_edf(file, eog=None, misc=None, stim_channel='auto', exclude=(), infer_types=False, include=None, preload=True, units=None, encoding='utf8', verbose=None)
    # By default read_raw_edf convert units to V
    raw = MDD_preprocess(raw)
    raw_MDD.append(raw.get_data())

In [ ]:
# M1 : Averaging using mean:

raw_MDD_avg = np.mean(raw_MDD, axis=0)
print(raw_MDD_avg)

del raw_MDD[:]
del raw_MDD
del eye_close_MDD[:]
del eye_close_MDD

In [ ]:
info = raw.info
raw_MDD = mne.io.RawArray(raw_MDD_avg, info)

Control group data (Online control group data eye closed)

In [ ]:
# PRE VS POST COMPARISON
eye_close_6 = '\\Depression-Sample-dataset-AIIMS\\Active\\PreetiSingh\\post\\' + '20230826225729_PreetiSingh_08.09.23_20_Eye Close'
eye_close_7 = '\\Depression-Sample-dataset-AIIMS\\Active\\Hemlata\\post\\' + '20231019110530_Hemlata_19.10.23_19A_Eye Close'
eye_close_8 = '\\Depression-Sample-dataset-AIIMS\\Active\\VinodKumarSharma\\post\\' + '20230901112451_VinodKumarSharma_11.10.23_20_Eye Close'
eye_close_9 = '\\Depression-Sample-dataset-AIIMS\\Sham\\JitenderKumar\\post\\' + '20230827174115_JitenderKumar_13.09.23_20_Eye Close'
eye_close_10 = '\\Depression-Sample-dataset-AIIMS\\Sham\\SeemaKumari\\post\\' + '20230829172634_SeemaKumari_23.9.23_20_Eye Close'
eye_close_control = [eye_close_6, eye_close_7, eye_close_8, eye_close_9, eye_close_10]

In [ ]:
# PRE VS POST COMPARISON
raw_control = []
# folder_path = os.getcwd()+'\\Depression-Sample-dataset-AIIMS\\'
for file in eye_close_control:
    file_path = os.getcwd()+ file + '.easy'
    raw = data_transformation_easy(file_path)
    # raw = mne.io.read_raw_edf(file, eog=None, misc=None, stim_channel='auto', exclude=(), infer_types=False, include=None, preload=True, units=None, encoding='utf8', verbose=None)
    # By default read_raw_edf convert units to V
    raw = MDD_preprocess(raw)
    raw_control.append(raw.get_data())

In [ ]:
# PRE VS POST COMPARISON
# M1 : Averaging using mean:
raw_control_avg = np.mean(raw_control, axis=0)
print(raw_control_avg)

del raw_control[:]
del raw_control
del eye_close_control[:]
del eye_close_control

In [ ]:
# PRE VS POST COMPARISON
info = raw.info
raw_control = mne.io.RawArray(raw_control_avg, info)

In [ ]:
# # Find control indexes
# file_path = os.getcwd() + '\\Depression-Sample-dataset-AIIMS\\' + 'Control\\' + 'derivatives\\cleaned_epochs\\'
# control_indexes = []
# for i in range(0, 111):
#     eeg_file_epoch = file_path + f'sub-{i+1:03d}\\ses-t1\\eeg\\sub-{i+1:03d}_ses-t1_task-resteyesc_desc-epochs_eeg.set'
#     epochs_data = mne.io.read_epochs_eeglab(eeg_file_epoch, events=None, event_id=None, eog=(), uint16_codec=None, montage_units='mm', verbose=None)
#     if len(epochs_data.get_data()) == 55:
#         control_indexes.append(i)

In [ ]:
# file_path = os.getcwd() + '\\Depression-Sample-dataset-AIIMS\\' + 'Control\\'
# raw_control = []
# for i in control_indexes:
#     eeg_file_raw = file_path + f'sub-{i+1:03d}\\ses-t1\\eeg\\sub-{i+1:03d}_ses-t1_task-resteyesc_eeg.edf'
#     raw = mne.io.read_raw_edf(eeg_file_raw, eog=None, misc=None, stim_channel='auto', exclude=(), infer_types=False, include=None, preload=False, units=None, encoding='utf8', verbose=None)
#     # By default read_raw_edf convert units to V
#     raw = control_preprocessing(raw, raw_MDD)
#     raw_control.append(raw.get_data())

In [ ]:
# del control_indexes[:]
# del control_indexes

In [ ]:
# raw_control_avg = np.mean(raw_control, axis=0)

# del raw_control[:]
# del raw_control

In [ ]:
# info = raw.info
# raw_control = mne.io.RawArray(raw_control_avg, info)

Saving Raw MDD and control data

In [ ]:
# raw_MDD.save("loadData/rawMDDpre5.fif", overwrite=True)
# raw_control.save("loadData/rawMDDpost5.fif", overwrite=True)

### Epoching

In [ ]:
duration = 4.0
overlap = 2.0 

samples_per_epoch = int(duration * SFREQ)
samples_per_overlap = int(overlap * SFREQ)

# Manually created events
start, stop = 0, samples_per_epoch
events = []
while stop <= len(raw_MDD):
    events.append([start, 0, 1]) 
    start += samples_per_overlap
    stop += samples_per_overlap

events = np.array(events)

3.1 Segmenting epochs for MDD

In [ ]:
epochs_MDD = mne.Epochs(raw_MDD, events, tmin=0, tmax=duration, baseline=None, detrend=1,
                    picks=None, preload=True, reject=None)
raw_MDD.plot(n_channels=len(raw_MDD.info['ch_names']), events=events, event_color={1:'r'}, scalings=SCALINGS)
epochs_MDD.plot(n_channels=len(raw_MDD.info['ch_names']), event_color={1:'r'}, events=None, scalings=SCALINGS)

3.2 Segmenting epochs for control

In [ ]:
epochs_control = mne.Epochs(raw_control, events, tmin=0, tmax=duration, baseline=None, detrend=1,
                    picks=None, preload=True, reject=None)
raw_control.plot(n_channels=len(raw_MDD.info['ch_names']), events=events, event_color={1:'r'}, scalings=SCALINGS)
epochs_control.plot(n_channels=len(raw_MDD.info['ch_names']), event_color={1:'r'}, events=None, scalings=SCALINGS)

In [ ]:
# file_path = os.getcwd() + '\\Depression-Sample-dataset-AIIMS\\' + 'Control\\' + 'derivatives\\cleaned_epochs\\'
# epochs_control = []
# for i in range(0, 111):
#     eeg_file_epoch = file_path + f'sub-{i+1:03d}\\ses-t1\\eeg\\sub-{i+1:03d}_ses-t1_task-resteyesc_desc-epochs_eeg.set'
#     epochs_data = mne.io.read_epochs_eeglab(eeg_file_epoch, events=None, event_id=None, eog=(), uint16_codec=None, montage_units='mm', verbose=None)
#     if len(epochs_data.get_data()) == 55:
#         cleaned_epoch = control_preprocessing(epochs_data, epochs_MDD, crop=False)
#         epochs_control.append(cleaned_epoch)

In [ ]:
# epochs_control_avg = np.mean(epochs_control, axis=0)
# print(epochs_control_avg)

# del epochs_control[:]
# del epochs_control

In [ ]:
# info = cleaned_epoch.info
# epochs_control = mne.EpochsArray(epochs_control_avg, info)
# epochs_control.plot(n_channels=len(raw_MDD.info['ch_names']), event_color={1:'r'}, events=None, scalings=SCALINGS)

Saving epoched raw and control data

In [ ]:
# epochs_MDD.save("loadData/epochsMDDpre5.fif", overwrite=True)
# epochs_control.save("loadData/epochsMDDpost5.fif", overwrite=True)

### 1. PSD graph plot between MDD and Control group

For resting state EEG channel, analyzing the overall average power across channels provides a holistic view of the brain's activity without emphasizing the specificity of individual channels.

In [ ]:
# def wavelet_plot(raw1, raw2, title):
#     '''
#     signal ----> breaks into frequency components/scales ----> WT computes coeffcients that represent signal's content 
#     at a specific scale ----->coeffs at lower level represent lower frequency components
     
#     Scales vs frequencies - lower scale = higher frequency (fine details)
#     larger coefficient represents higher energy at a sepcific scale
#     peaks in scale vs time plot = where energy is concentrated
#     broad distribution across scales = mix of frequencies

#     Find frequency component of interest 
#     Step1: Look for peaks (dominant frequencies)
#     Step2: Convert scale to frequency using frequency = SFREQ/(2**scale)
#     Step 3: Compare across time
#     Step 4: Statistical analysis

#     '''
#     # Average channel wavelet transform
#     raw1_avg = np.mean(raw1.get_data(), axis=0)
#     raw2_avg = np.mean(raw2.get_data(), axis=0)

#     # Individual channels wavelet transform
#     t = np.arange(0, 150, 1/SFREQ)
#     ts = t[:-1]
    
#     wavelet = 'db13'
#     level = 4 # level of decomposition based on your signal characteristics
 
#     coeffs1 = pywt.wavedec(raw1_avg, wavelet, level=level)    
#     coeffs2 = pywt.wavedec(raw2_avg, wavelet, level=level)

#     plt.figure(figsize=(10, 6))
#     for i in range(level+1):
#         if i==0:
#             plt.plot(t, raw1_avg, label='MDD raw')
#         plt.plot(t, pywt.upcoef('a', coeffs1[i], wavelet, level=level)[:len(t)], label=f'MDD - Level {i}')
#         if i==0:
#             plt.plot(t, raw2_avg, label='Control raw')
#         plt.plot(t, pywt.upcoef('a', coeffs2[i], wavelet, level=level)[:len(t)], label=f'Control - Level {i}')
#         plt.title('DWT')
#         plt.xlabel('Time')
#         plt.ylabel('Amplitude')
#         plt.legend()
#         plt.show()

# wavelet_plot(raw_MDD, raw_control, "gjhggj")

In [4]:
# Amplitude plots between both groups
epochs_MDD_avg = epochs_MDD['1'].average()
epochs_control_avg = epochs_control['1'].average()
# evokeds = dict(epochs_MDD=epochs_MDD)
fig_MDD = epochs_MDD_avg.plot(titles='MDD', time_unit = 'ms')
fig_control = epochs_control_avg.plot(titles='control', time_unit = 'ms')

NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).


1.1 PSD using plot_psd

In [5]:
fig, ax = plt.subplots()
#plot_psd uses welch method for continuous data
raw_MDD.plot_psd(picks=raw_MDD.info['ch_names'], average=True, fmin=FMIN, fmax=FMAX, ax=ax, show=False, color='blue', dB=False)
raw_control.plot_psd(picks=raw_control.info['ch_names'], average=True, fmin=FMIN, fmax=FMAX, ax=ax, show=False, color='red', dB=False)

# dB = True plots PSD in decibels (logarithmic)
# different n_fft compared to psd_array_welch
ax.set_xlabel('Frequency (Hz)')
ax.set_ylabel('Power/Frequency (microV^2/Hz)')
ax.set_title('Power Spectral Density Comparison')
ax.legend() 
plt.ylim(0, 5)
plt.show()

NOTE: plot_psd() is a legacy function. New code should use .compute_psd().plot().
Effective window size : 4.096 (s)
NOTE: plot_psd() is a legacy function. New code should use .compute_psd().plot().
Effective window size : 4.096 (s)


No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.


1.2 Average of power using welch method

In [6]:
labels = np.arange(0, FMAX)
# welch always gives positive psd
psd_MDD, frequencies = mne.time_frequency.psd_array_welch(raw_MDD.get_data(), fmin=FMIN, fmax=FMAX, sfreq=SFREQ)
psd_control, frequencies = mne.time_frequency.psd_array_welch(raw_control.get_data(), fmin=FMIN, fmax=FMAX, sfreq=SFREQ)
avg_abs_power_MDD, avg_abs_power_control = np.mean(psd_MDD, axis=0), np.mean(psd_control, axis=0) 

plt.figure()
plt.plot(frequencies, avg_abs_power_MDD, color='blue')
plt.plot(frequencies, avg_abs_power_control, color='red')
plt.title('Welch - Average Power-blue(MDD)-red(Control)')
plt.xlabel('Frequency (Hz)')
plt.xticks(labels, labels, rotation ='vertical') 
plt.ylabel('Power (V^2/Hz)')
plt.show()

Effective window size : 0.512 (s)


Effective window size : 0.512 (s)


1.3 Statistical testing between psds of raw

1.3.1 Plotting Histogram

Shows if the data is bell shaped, skewed (positive or negative), uniform etc. Central tendency - highest peak in histogram. Spread - width of distribution

In [7]:
MDD_avg = np.mean(raw_MDD.get_data(), axis=0)
plt.hist(MDD_avg, bins='auto', alpha=0.7, edgecolor='black')
plt.title(f'Histogram of MDD Data - averaged across all channels')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.show()

In [8]:
control_avg = np.mean(raw_control.get_data(), axis=0)
plt.hist(control_avg, bins='auto', alpha=0.7, edgecolor='black')
plt.title(f'Histogram of control Data - averaged across all channels')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.show()

In [9]:
print("MDD mean: ", np.mean(MDD_avg, axis=0))
print("Control mean: ", np.mean(control_avg, axis=0))

MDD mean:  -2.0070764813061382e-16
Control mean:  1.0924363901150833e-15


1.3.2 Calculate variance of both groups

In [10]:
variance_MDD = np.var(psd_MDD, ddof=1) 
variance_control = np.var(psd_control, ddof=1)
print("MDD variance: ", variance_MDD)
print("Control variance: ", variance_control)

MDD variance:  6.2507817976989105e-24
Control variance:  1.5712764319411083e-23


1.3.3 Find differences between the means of two independent groups

For example, null hypothesis: there is no significant difference between groups (ie means are equal).
alternative hypothesis: there is a significant difference between groups
t-test : compares the differences between group means to expected variability in data

In [11]:
p_values = np.zeros(32)
t = np.zeros(32)
for i in range(32):
    t[i], p_values[i] = ttest_ind(psd_MDD[i, :], psd_control[i, :])
# independent t-test comparison : equal_var = True
# welch's t-test comparison: equal_var = False
print("Raw Data PSD Comparison Results:")
print("T-statistic:", t)
print("P-values:", p_values) # probability of getting t-statistic >= what we got

Raw Data PSD Comparison Results:
T-statistic: [-0.49523536  0.14744193 -0.31393649 -0.97294841 -0.01139994 -0.297804
  0.36400093 -0.83812901 -0.05735324  0.05408089 -0.15951497  0.16853522
  0.88251566  0.64645463  0.0807843   0.15865084  1.73768353 -0.68993094
  1.50677987  1.57381697  0.9410575  -0.72802323  0.75261838 -0.74717936
 -0.9011082  -0.75598126  0.50658117  0.48093111 -0.16564691  1.53928994
  0.36200718  0.94130491]
P-values: [0.62289827 0.88345677 0.7550529  0.33589763 0.99095589 0.76725444
 0.71760068 0.40648827 0.95452348 0.95711553 0.87399316 0.8669346
 0.3822942  0.52134289 0.93597984 0.87466993 0.08926211 0.49386072
 0.13901363 0.1226937  0.35181353 0.47045615 0.45568713 0.45892976
 0.37243687 0.45368895 0.61497796 0.63294841 0.8691936  0.13089495
 0.71907953 0.35168819]


In [13]:
t_statistic, p_values = ttest_ind(np.mean(psd_MDD, axis=0), np.mean(psd_control, axis=0), equal_var=False)
# independent t-test comparison : equal_var = True
# welch's t-test comparison: equal_var = False
print("Raw Data PSD Comparison Results:")
print("T-statistic:", t_statistic)
print("P-values:", p_values) # probability of getting t-statistic >= what we got

Raw Data PSD Comparison Results:
T-statistic: -0.03914189465736664
P-values: 0.9689746759463302


If p value < 0.005, we reject the null hypothesis

### 2. PLI and construction of brain function matrices

In [12]:
freq_bands = [(0.01, 4), (4,8), (8, 10), (10, 13)]
mapping = {0: 'delta', 1: 'theta', 2: 'alpha1', 3:'alpha2'}
connectivity = {}

In [13]:
# pli method always gives positive correlations
def connectivity_matrix(epochs, i):
    return spectral_connectivity_epochs(
    epochs, method='pli', mode='multitaper', sfreq=SFREQ,
    fmin=freq_bands[i][0], fmax=freq_bands[i][1], faverage=True, n_jobs=1)


In [14]:
len(epochs_MDD.get_data())

Loading data for 73 events and 2001 original time points ...


73

In [15]:
n_channels = len(raw_MDD.info['ch_names'])
for i in range(len(freq_bands)):
    con = connectivity_matrix(epochs_MDD, i)
    connectivity[f'MDD-{mapping[i]}'] = con.get_data().reshape((n_channels, n_channels))

    con = connectivity_matrix(epochs_control, i)
    connectivity[f'Control-{mapping[i]}'] = con.get_data().reshape((n_channels, n_channels))

    # Make matrix symmetric
    for row in range(n_channels):
        for col in range(n_channels):
            connectivity[f'MDD-{mapping[i]}'][row][col] = connectivity[f'MDD-{mapping[i]}'][col][row]
            connectivity[f'Control-{mapping[i]}'][row][col] = connectivity[f'Control-{mapping[i]}'][col][row]
    

Connectivity computation...
only using indices for lower-triangular matrix
    computing connectivity for 496 connections
    using t=0.000s..4.000s for estimation (2001 points)
    frequencies: 0.2Hz..4.0Hz (16 points)
    connectivity scores will be averaged for each band
    Using multitaper spectrum estimation with 7 DPSS windows
    the following metrics will be computed: PLI
    computing connectivity for epoch 1
    computing connectivity for epoch 2
    computing connectivity for epoch 3
    computing connectivity for epoch 4
    computing connectivity for epoch 5
    computing connectivity for epoch 6
    computing connectivity for epoch 7
    computing connectivity for epoch 8
    computing connectivity for epoch 9
    computing connectivity for epoch 10
    computing connectivity for epoch 11
    computing connectivity for epoch 12
    computing connectivity for epoch 13
    computing connectivity for epoch 14


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: There were no Annotations stored in <EpochsFIF |  73 events (all good), 0 – 4 s, baseline off, ~47 kB, data not loaded,
 '1': 73>, so metadata was not modified.
  return spectral_connectivity_epochs(
C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: fmin=0.010 Hz corresponds to 0.040 < 5 cycles based on the epoch length 4.002 sec, need at least 500.000 sec epochs or fmin=1.249. Spectrum estimate will be unreliable.
  return spectral_connectivity_epochs(


    computing connectivity for epoch 15
    computing connectivity for epoch 16
    computing connectivity for epoch 17
    computing connectivity for epoch 18
    computing connectivity for epoch 19
    computing connectivity for epoch 20
    computing connectivity for epoch 21
    computing connectivity for epoch 22
    computing connectivity for epoch 23
    computing connectivity for epoch 24
    computing connectivity for epoch 25
    computing connectivity for epoch 26
    computing connectivity for epoch 27
    computing connectivity for epoch 28
    computing connectivity for epoch 29
    computing connectivity for epoch 30
    computing connectivity for epoch 31
    computing connectivity for epoch 32
    computing connectivity for epoch 33
    computing connectivity for epoch 34
    computing connectivity for epoch 35
    computing connectivity for epoch 36
    computing connectivity for epoch 37
    computing connectivity for epoch 38
    computing connectivity for epoch 39


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: There were no Annotations stored in <EpochsFIF |  72 events (all good), 0 – 4 s, baseline off, ~47 kB, data not loaded,
 '1': 72>, so metadata was not modified.
  return spectral_connectivity_epochs(
C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: fmin=0.010 Hz corresponds to 0.040 < 5 cycles based on the epoch length 4.002 sec, need at least 500.000 sec epochs or fmin=1.249. Spectrum estimate will be unreliable.
  return spectral_connectivity_epochs(


    computing connectivity for epoch 17
    computing connectivity for epoch 18
    computing connectivity for epoch 19
    computing connectivity for epoch 20
    computing connectivity for epoch 21
    computing connectivity for epoch 22
    computing connectivity for epoch 23
    computing connectivity for epoch 24
    computing connectivity for epoch 25
    computing connectivity for epoch 26
    computing connectivity for epoch 27
    computing connectivity for epoch 28
    computing connectivity for epoch 29
    computing connectivity for epoch 30
    computing connectivity for epoch 31
    computing connectivity for epoch 32
    computing connectivity for epoch 33
    computing connectivity for epoch 34
    computing connectivity for epoch 35
    computing connectivity for epoch 36
    computing connectivity for epoch 37
    computing connectivity for epoch 38
    computing connectivity for epoch 39
    computing connectivity for epoch 40
    computing connectivity for epoch 41


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: There were no Annotations stored in <EpochsFIF |  73 events (all good), 0 – 4 s, baseline off, ~47 kB, data not loaded,
 '1': 73>, so metadata was not modified.
  return spectral_connectivity_epochs(


    computing connectivity for epoch 19
    computing connectivity for epoch 20
    computing connectivity for epoch 21
    computing connectivity for epoch 22
    computing connectivity for epoch 23
    computing connectivity for epoch 24
    computing connectivity for epoch 25
    computing connectivity for epoch 26
    computing connectivity for epoch 27
    computing connectivity for epoch 28
    computing connectivity for epoch 29
    computing connectivity for epoch 30
    computing connectivity for epoch 31
    computing connectivity for epoch 32
    computing connectivity for epoch 33
    computing connectivity for epoch 34
    computing connectivity for epoch 35
    computing connectivity for epoch 36
    computing connectivity for epoch 37
    computing connectivity for epoch 38
    computing connectivity for epoch 39
    computing connectivity for epoch 40
    computing connectivity for epoch 41
    computing connectivity for epoch 42
    computing connectivity for epoch 43


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: There were no Annotations stored in <EpochsFIF |  72 events (all good), 0 – 4 s, baseline off, ~47 kB, data not loaded,
 '1': 72>, so metadata was not modified.
  return spectral_connectivity_epochs(


    computing connectivity for epoch 13
    computing connectivity for epoch 14
    computing connectivity for epoch 15
    computing connectivity for epoch 16
    computing connectivity for epoch 17
    computing connectivity for epoch 18
    computing connectivity for epoch 19
    computing connectivity for epoch 20
    computing connectivity for epoch 21
    computing connectivity for epoch 22
    computing connectivity for epoch 23
    computing connectivity for epoch 24
    computing connectivity for epoch 25
    computing connectivity for epoch 26
    computing connectivity for epoch 27
    computing connectivity for epoch 28
    computing connectivity for epoch 29
    computing connectivity for epoch 30
    computing connectivity for epoch 31
    computing connectivity for epoch 32
    computing connectivity for epoch 33
    computing connectivity for epoch 34
    computing connectivity for epoch 35
    computing connectivity for epoch 36
    computing connectivity for epoch 37


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: There were no Annotations stored in <EpochsFIF |  73 events (all good), 0 – 4 s, baseline off, ~47 kB, data not loaded,
 '1': 73>, so metadata was not modified.
  return spectral_connectivity_epochs(


    computing connectivity for epoch 18
    computing connectivity for epoch 19
    computing connectivity for epoch 20
    computing connectivity for epoch 21
    computing connectivity for epoch 22
    computing connectivity for epoch 23
    computing connectivity for epoch 24
    computing connectivity for epoch 25
    computing connectivity for epoch 26
    computing connectivity for epoch 27
    computing connectivity for epoch 28
    computing connectivity for epoch 29
    computing connectivity for epoch 30
    computing connectivity for epoch 31
    computing connectivity for epoch 32
    computing connectivity for epoch 33
    computing connectivity for epoch 34
    computing connectivity for epoch 35
    computing connectivity for epoch 36
    computing connectivity for epoch 37
    computing connectivity for epoch 38
    computing connectivity for epoch 39
    computing connectivity for epoch 40
    computing connectivity for epoch 41
    computing connectivity for epoch 42


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: There were no Annotations stored in <EpochsFIF |  72 events (all good), 0 – 4 s, baseline off, ~47 kB, data not loaded,
 '1': 72>, so metadata was not modified.
  return spectral_connectivity_epochs(


    computing connectivity for epoch 21
    computing connectivity for epoch 22
    computing connectivity for epoch 23
    computing connectivity for epoch 24
    computing connectivity for epoch 25
    computing connectivity for epoch 26
    computing connectivity for epoch 27
    computing connectivity for epoch 28
    computing connectivity for epoch 29
    computing connectivity for epoch 30
    computing connectivity for epoch 31
    computing connectivity for epoch 32
    computing connectivity for epoch 33
    computing connectivity for epoch 34
    computing connectivity for epoch 35
    computing connectivity for epoch 36
    computing connectivity for epoch 37
    computing connectivity for epoch 38
    computing connectivity for epoch 39
    computing connectivity for epoch 40
    computing connectivity for epoch 41
    computing connectivity for epoch 42
    computing connectivity for epoch 43
    computing connectivity for epoch 44
    computing connectivity for epoch 45


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: There were no Annotations stored in <EpochsFIF |  73 events (all good), 0 – 4 s, baseline off, ~47 kB, data not loaded,
 '1': 73>, so metadata was not modified.
  return spectral_connectivity_epochs(


    computing connectivity for epoch 20
    computing connectivity for epoch 21
    computing connectivity for epoch 22
    computing connectivity for epoch 23
    computing connectivity for epoch 24
    computing connectivity for epoch 25
    computing connectivity for epoch 26
    computing connectivity for epoch 27
    computing connectivity for epoch 28
    computing connectivity for epoch 29
    computing connectivity for epoch 30
    computing connectivity for epoch 31
    computing connectivity for epoch 32
    computing connectivity for epoch 33
    computing connectivity for epoch 34
    computing connectivity for epoch 35
    computing connectivity for epoch 36
    computing connectivity for epoch 37
    computing connectivity for epoch 38
    computing connectivity for epoch 39
    computing connectivity for epoch 40
    computing connectivity for epoch 41
    computing connectivity for epoch 42
    computing connectivity for epoch 43
    computing connectivity for epoch 44


C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\1345682627.py:3: RuntimeWarning: There were no Annotations stored in <EpochsFIF |  72 events (all good), 0 – 4 s, baseline off, ~47 kB, data not loaded,
 '1': 72>, so metadata was not modified.
  return spectral_connectivity_epochs(


    computing connectivity for epoch 18
    computing connectivity for epoch 19
    computing connectivity for epoch 20
    computing connectivity for epoch 21
    computing connectivity for epoch 22
    computing connectivity for epoch 23
    computing connectivity for epoch 24
    computing connectivity for epoch 25
    computing connectivity for epoch 26
    computing connectivity for epoch 27
    computing connectivity for epoch 28
    computing connectivity for epoch 29
    computing connectivity for epoch 30
    computing connectivity for epoch 31
    computing connectivity for epoch 32
    computing connectivity for epoch 33
    computing connectivity for epoch 34
    computing connectivity for epoch 35
    computing connectivity for epoch 36
    computing connectivity for epoch 37
    computing connectivity for epoch 38
    computing connectivity for epoch 39
    computing connectivity for epoch 40
    computing connectivity for epoch 41
    computing connectivity for epoch 42


Statistical analysis using NBS to cross check frequency band of interest calculated using small world network (binarization method)

In [ ]:
for i in range(len(freq_bands)):
    print()
    # find NBS in all freq_bands 
    # Find freq band sof interest 
    # FInd mean and SD for all adjacency matrices for both groups 
    # make matrix in such a way that channels closer are together ? TODO: - 0 values in diagonal
    # plot adjacency matrix for both groups in all bands of interest

In [16]:
print((connectivity.keys()))

dict_keys(['MDD-delta', 'Control-delta', 'MDD-theta', 'Control-theta', 'MDD-alpha1', 'Control-alpha1', 'MDD-alpha2', 'Control-alpha2'])


In [ ]:
# # ALTERNATIVE: PLI calculation in Raw Python

# def calculate_pli(data):
#     # data = EEG data of channel Ci and Cj for 1 epoch (2000 data points (4s X 500fs))
#     analytic_signal = hilbert(data)
#     instantaneous_phase = np.angle(analytic_signal)
#     return np.abs(np.mean(np.sign(np.diff(instantaneous_phase, axis=0))))

# fun_connectivity = []
# for k in range(len(epochs)):
#     pli_matrix = [[0 for i in range(len(raw_cleaned.info['ch_names']))] for j in range(len(raw_cleaned.info['ch_names']))]
#     for i in range(len(raw_cleaned.info['ch_names'])):
#         for j in range(i+1, len(raw_cleaned.info['ch_names'])):
#             pli_matrix[i][j] = pli_matrix[j][i] = calculate_pli([epochs[k].get_data(fmin = freq_bands[0][0], fmax=freq_bands[-1][-1])[0][i], epochs[k].get_data(fmin = freq_bands[0][0], fmax=freq_bands[-1][-1])[0][j]])

#     fun_connectivity.append(pli_matrix)
# conn = np.mean(fun_connectivity, axis=0)

### M1 - 4. Small World Index

In [20]:
optimal_threshold = {}
edges_MDD = {}
edges_control = {}
from scipy.stats import kurtosis, zscore, ttest_ind

for i in range(len(freq_bands)):
    
    MDD_average = calculate_avergae_components(nx.from_numpy_array(connectivity[f'MDD-{mapping[i]}']))
    Lw_MDD = MDD_average[0]
    Cw_MDD = MDD_average[3]

    control_average = calculate_avergae_components(nx.from_numpy_array(connectivity[f'Control-{mapping[i]}']))
    Lw_control = control_average[0]
    Cw_control = control_average[3]


    # Generating 50 random networks with same number of vertices and edges 
    random_networks = [nx.gnm_random_graph(n_channels, 496) for _ in range(50)]
    # Average of clustering coefficients of all random networks and average of shortest path length of
    # all random networks
    Crand = np.mean([nx.average_clustering(G) for G in random_networks])
    Lrand = np.mean([nx.average_shortest_path_length(G) for G in random_networks])

    small_world_index_MDD =  (Cw_MDD/Crand)/(Lw_MDD/Lrand)
    small_world_index_control = (Cw_control/Crand)/(Lw_control/Lrand)
    swi_ratio = small_world_index_MDD/small_world_index_control

    thresholds = np.arange(0.1, 0.9, 0.002)
    edges_MDD[mapping[i]] = []
    edges_control[mapping[i]] = []

    ratios = []
    for threshold in thresholds:
        binarized_MDD = connectivity[f'MDD-{mapping[i]}'] > threshold
        binarized_control = connectivity[f'Control-{mapping[i]}'] > threshold

        edges_MDD[mapping[i]].append(nx.from_numpy_array(binarized_MDD).number_of_edges())
        edges_control[mapping[i]].append(nx.from_numpy_array(binarized_control).number_of_edges())

        # TODO: Cross check should we ignore thresholds which result in matrix to be not connected ?
        MDD_average_binarized = calculate_avergae_components(nx.from_numpy_array(binarized_MDD))
        Lw_MDD_binarized = MDD_average_binarized[0]
        Cw_MDD_binarized = MDD_average_binarized[3]
        control_average_binarized = calculate_avergae_components(nx.from_numpy_array(binarized_control))
        Lw_control_binarized = control_average_binarized[0]
        Cw_control_binarized = control_average_binarized[3]
        swi_binarized_MDD =  (Cw_MDD_binarized/Crand)/(Lw_MDD_binarized/Lrand)
        swi_binarized_control = (Cw_control_binarized/Crand)/(Lw_control_binarized/Lrand)
        
        swi_ratio_binarized =  swi_binarized_MDD/swi_binarized_control
        ratios.append(swi_ratio_binarized)

    optimal_threshold[mapping[i]] = thresholds[np.argmax(np.abs(ratios))] #TODO: ratios - swi_ratio
    # OR remove swi_ratio and related code above

    t_stat, p_value = ttest_ind(np.mean(connectivity[f'MDD-{mapping[i]}'], axis=0), np.mean(connectivity[f'Control-{mapping[i]}'], axis=0)) 

    # _, p_value = mne.stats.ttest_ind_no_p(connectivity[f'MDD-{mapping[i]}'], connectivity[f'Control-{mapping[i]}'])
    if p_value < 0.005: # Reject the null hypotheses
        print(f"Optimal Threshold: {optimal_threshold[mapping[i]]} (Significant)", p_value)

    # plt.plot(thresholds, ratios, label='Threshold Ratios')
    # plt.axhline(swi_ratio, color='red', linestyle='--', label=' SWI ratio (MDD/Control)')
    # plt.xlabel(f'Threshold-{mapping[i]}')
    # plt.ylabel('Ratio')
    # plt.legend()
    # plt.show()
print(optimal_threshold)

C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\523292313.py:50: RuntimeWarning: invalid value encountered in scalar divide
  swi_ratio_binarized =  swi_binarized_MDD/swi_binarized_control
C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\523292313.py:47: RuntimeWarning: invalid value encountered in scalar divide
  swi_binarized_MDD =  (Cw_MDD_binarized/Crand)/(Lw_MDD_binarized/Lrand)
C:\Users\vishw\AppData\Local\Temp\ipykernel_19780\523292313.py:48: RuntimeWarning: invalid value encountered in scalar divide
  swi_binarized_control = (Cw_control_binarized/Crand)/(Lw_control_binarized/Lrand)


Optimal Threshold: 0.5720000000000004 (Significant) 8.317776485975295e-14
Optimal Threshold: 0.8160000000000006 (Significant) 6.94800957753124e-05
{'delta': 0.4340000000000003, 'theta': 0.5720000000000004, 'alpha1': 0.8160000000000006, 'alpha2': 0.8420000000000006}


In [ ]:
# for i in range(len(freq_bands)):
#     optimal_threshold[mapping[i]]  += 0.1
# print(optimal_threshold)

### M2 - 4. Community structure

In [21]:
from networkx.algorithms.community import greedy_modularity_communities
import networkx as nx
# Calculate the participation coefficient for each node
def participation_coefficient(node, modularity_matrix):
    k_in = np.sum(modularity_matrix[node, :])
    k_out = np.sum(modularity_matrix) - k_in
    q = modularity_matrix.shape[0]
    pc = 1 - ((k_in / q) ** 2 + (k_out / q) ** 2)
    return pc

def community_structure(G):
    # Compute community structure (Louvain algorithm)
    partition = list(nx.algorithms.community.modularity_max.greedy_modularity_communities(G)[0])
    # pi_scores = nx.algorithms.community.indicators.participation(G, partition)(G)

    print(nx.modularity_matrix(G))

    # plot network with community structure 
    # pos = nx.spring_layout(G)
    # colors = [partition[node] for node in G.nodes]
    # plt.figure(figsize=(10, 8))
    # nx.draw(G, pos, node_color=colors, with_labels=True, cmap=plt.cm.Paired, node_size=300)
    # plt.title("Community structure")
    # plt.show()

    num_nodes = len(G.nodes)
    mod_matrix = np.zeros((num_nodes, num_nodes))

    # Find modularity matrix
    for i, j, _ in G.edges(data=True):
        mod_matrix[i][j] = 1 if partition[i] == partition[j] else 0

    pi_values = np.zeros(num_nodes)
    for node in range(num_nodes):
        pi_values[node] = participation_coefficient(node, mod_matrix)

    # Rank-order the PI scores (lowest to highest)
    ranked_pi = np.argsort(pi_values) + 1
    return ranked_pi

In [22]:
for i in range(len(freq_bands)):
    # Values ranging from -1 to 1
    diff_matrix = nx.from_numpy_array(connectivity[f'MDD-{mapping[i]}'] - connectivity[f'Control-{mapping[i]}'])
    print(np.min(connectivity[f'MDD-{mapping[i]}'] - connectivity[f'Control-{mapping[i]}']), np.max(connectivity[f'MDD-{mapping[i]}'] - connectivity[f'Control-{mapping[i]}']))
    ranked_pi = community_structure(diff_matrix)

-0.4651826484018265 0.3002758751902588
[[-0.96875  0.03125  0.03125 ...  0.03125  0.03125  0.03125]
 [ 0.03125 -0.96875  0.03125 ...  0.03125  0.03125  0.03125]
 [ 0.03125  0.03125 -0.96875 ...  0.03125  0.03125  0.03125]
 ...
 [ 0.03125  0.03125  0.03125 ... -0.96875  0.03125  0.03125]
 [ 0.03125  0.03125  0.03125 ...  0.03125 -0.96875  0.03125]
 [ 0.03125  0.03125  0.03125 ...  0.03125  0.03125 -0.96875]]
-0.7693588280060883 0.48185407153729076
[[-0.96875  0.03125  0.03125 ...  0.03125  0.03125  0.03125]
 [ 0.03125 -0.96875  0.03125 ...  0.03125  0.03125  0.03125]
 [ 0.03125  0.03125 -0.96875 ...  0.03125  0.03125  0.03125]
 ...
 [ 0.03125  0.03125  0.03125 ... -0.96875  0.03125  0.03125]
 [ 0.03125  0.03125  0.03125 ...  0.03125 -0.96875  0.03125]
 [ 0.03125  0.03125  0.03125 ...  0.03125  0.03125 -0.96875]]
-0.7593226788432268 0.6359874429223745
[[-0.96875  0.03125  0.03125 ...  0.03125  0.03125  0.03125]
 [ 0.03125 -0.96875  0.03125 ...  0.03125  0.03125  0.03125]
 [ 0.03125  0.03

### M3 - 4. Threshold using saturation

In [23]:
for i in range(len(freq_bands)):
    plt.plot(thresholds, edges_MDD[mapping[i]])
    plt.plot(thresholds, edges_control[mapping[i]])
    plt.title(f'{mapping[i]} Threshold comparison (blue - MDD, red-Control)')
    plt.xlabel('Thresholds')
    plt.ylabel('Number of edges')
    plt.show()

In [ ]:
# # To remove:
# optimal_threshold['delta'] = 0.442
# optimal_threshold['theta'] =  0.529
# optimal_threshold['alpha1'] = 0.786
# optimal_threshold['alpha2'] = 0.741

### M4 - 4. ML algorithm

In [ ]:
# raw_MDD.info

### 5. Binarization on functional connectivity matrices

In [43]:
binarized_matrix = {}
for i in range(len(freq_bands)):
    binarized_matrix[f'MDD-{mapping[i]}'] = connectivity[f'MDD-{mapping[i]}'] > optimal_threshold[mapping[i]]
    binarized_matrix[f'Control-{mapping[i]}'] = connectivity[f'Control-{mapping[i]}'] > optimal_threshold[mapping[i]]
print(binarized_matrix.keys())

dict_keys(['MDD-delta', 'Control-delta', 'MDD-theta', 'Control-theta', 'MDD-alpha1', 'Control-alpha1', 'MDD-alpha2', 'Control-alpha2'])


Find number of links in each graph

In [44]:
for i in range(len(freq_bands)):
    links_MDD = 0
    links_control = 0

    for row in range(n_channels):
        for col in range(row+1):
            if binarized_matrix[f'MDD-{mapping[i]}'][row][col] == 1:
                links_MDD+=1
            if binarized_matrix[f'Control-{mapping[i]}'][row][col] == 1:
                links_control+=1

    print(f'MDD-{mapping[i]}-number of links: K=', links_MDD)
    print(f'Control-{mapping[i]}-number of links: K=', links_control)

MDD-delta-number of links: K= 5
Control-delta-number of links: K= 18
MDD-theta-number of links: K= 0
Control-theta-number of links: K= 53
MDD-alpha1-number of links: K= 0
Control-alpha1-number of links: K= 18
MDD-alpha2-number of links: K= 0
Control-alpha2-number of links: K= 7


In [21]:
# Yellow - Higher synchronisation
for i in range(len(binarized_matrix)//2):
    # i = 0, 1, 2
    plt.figure(figsize=(12, 4))
    for j in range(2):
        # j = 0, 1
        plt.subplot(1, 2, j+1)
        plt.imshow(list(binarized_matrix.values())[2*i+j], interpolation='none')
        plt.title(f'Functional connectivity - {list(binarized_matrix)[2*i+j]} - Visualization')
        plt.xticks([_ for _ in range(n_channels)], raw_MDD.info['ch_names'], rotation='vertical')
        plt.yticks([_ for _ in range(n_channels)], raw_MDD.info['ch_names'], rotation='horizontal')
        plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.show()

### 6. Difference matrix

In [45]:
def return_index(channels_list, raw):
    indexes = []
    for channel in channels_list:
        for i in range(len(raw.info['ch_names'])):
            if raw.info['ch_names'][i]==channel:
                indexes.append(i)
    return(indexes)

In [46]:
central_channels = return_index(['Pz', 'Oz', 'Fz', 'Cz'], raw_MDD)
central_channels
raw_MDD.info['bads'] = []

In [ ]:
# ALL_CHANNELS = np.array(['P8', 'T8', 'CP6', 'FC6', 'F8', 'F4', 'C4', 'P4', 'AF4', 'Fp2',
#        'Fp1', 'AF3', 'Fz', 'FC2', 'Cz', 'CP2', 'PO3', 'O1', 'Oz', 'O2',
#        'PO4', 'Pz', 'CP1', 'FC1', 'P3', 'C3', 'F3', 'F7', 'FC5', 'CP5',
#        'T7', 'P7'])
# def set_montage(raw):
#     mont1020 = mne.channels.make_standard_montage('standard_1020')
#     ind = [i for (i, channel) in enumerate(mont1020.ch_names) if channel in ALL_CHANNELS]
#     mont1020_new = mont1020.copy()
#     mont1020_new.ch_names = [mont1020.ch_names[x] for x in ind]
#     kept_channel_info = [mont1020.dig[x+3] for x in ind]
#     mont1020_new.dig = mont1020.dig[0:3]+kept_channel_info
#     print("sjkghdkgu", mont1020_new)
#     return raw.set_montage(mont1020_new)

In [47]:
difference_matrix = {}
from mne.io.pick import _picks_to_idx
for i in range(len(freq_bands)):
    difference_matrix[mapping[i]] = binarized_matrix[f'Control-{mapping[i]}'].astype(int) - binarized_matrix[f'MDD-{mapping[i]}'].astype(int) 
    for k in range(n_channels):
        for l in range(n_channels):
            if difference_matrix[mapping[i]][k][l] == -1 or k in central_channels or l in central_channels:
                difference_matrix[mapping[i]][k][l] = 0

    # Yellow - Higher synchronisation
    plt.imshow(difference_matrix[mapping[i]], interpolation='none')
    plt.title(f'Functional connectivity - {[mapping[i]]} - Visualization')
    plt.xticks([_ for _ in range(n_channels)], raw_MDD.info['ch_names'], rotation='vertical')
    plt.yticks([_ for _ in range(n_channels)], raw_MDD.info['ch_names'], rotation='horizontal')
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.show()

    # epochs_MDD = set_montage(epochs_MDD)

    # plot_sensors_connectivity(
    #     raw_MDD.info,
    #     difference_matrix[mapping[i]],
    #     cbar_label=f'{mapping[i]}-Connectivity',
    #     )

ERROR:root:Cannot activate multiple GUI eventloops


ERROR:root:Cannot activate multiple GUI eventloops
ERROR:root:Cannot activate multiple GUI eventloops
ERROR:root:Cannot activate multiple GUI eventloops


In [ ]:
# from nilearn import plotting
# from nilearn.connectome import ConnectivityMeasure
# from nilearn.maskers import MultiNiftiLabelsMasker
# from nilearn import datasets

# # Load MNI152 atlas
# atlas = datasets.fetch_atlas_aal()

# # Extract MNI coordinates for 32 regions
# num_regions = 31*3
# coordinates = atlas.indices[:num_regions]
# # coordinates = atlas.region_coords[region_indices]

# # coordinates = raw_MDD.plot_sensors()
# print(raw_MDD.info, coordinates)

# # Plot the connectivity matrix
# plotting.plot_connectome(adjacency_matrix=binarized_matrix['MDD-alpha1'], node_coords=coordinates)
# plotting.show()

In [42]:
selected_channels = {}
for i in range(len(freq_bands)):
    selected_channels[mapping[i]] = []
    for ch in range(32):
        # TODO: instead of number of edges wise, we can explore other algorithm
        if len(nx.from_numpy_array(difference_matrix[mapping[i]]).edges(ch)) >=6:
            selected_channels[mapping[i]].append(raw_MDD.info['ch_names'][ch])
print(selected_channels)

{'delta': ['C3'], 'theta': ['O2', 'FC1', 'C3', 'T7'], 'alpha1': ['C3'], 'alpha2': []}


Create dictionary of Regions in brain vs channels

In [29]:
regionvschannel = {
    'LC': ['C3', 'CP1', 'CP5', 'FC1', 'FC5'], # Left central 
    'LF': ['FP1', 'AF3', 'F3', 'F7'], # Left frontal
    'LT': ['T7'], # Left temporal
    'LPO': ['PO3',  'P3', 'P7', 'O1'], # Left parietal-occipital
    'RC': ['CP6', 'FC6', 'C4', 'FC2', 'CP2',], # Right central 
    'RF': ['F8', 'F4', 'AF4', 'FP2'], # Right frontal
    'RT': ['T8'], # Right temporal
    'RPO': ['P8', 'P4', 'PO4', 'O2'] , # Right parietal-occipital
}

In [30]:
# for i in range(len(freq_bands)):
selected_regions = {}
# selected_regions['alpha2'] = ['RPO', 'LT', 'LF', 'LC']
# selected_regions['alpha1'] = ['LT', 'LC', 'LF', 'RPO'] # 1 in RPO
# selected_regions['theta'] = ['LC', 'LF'] # 1 in LC and 1 in LF
# selected_regions['delta'] =  ['LF', 'LC', 'RF', 'RC'] # 1-1 in 'LC', 'RF', 'RC'
selected_regions['delta'] =  ['LF', 'LC', 'RT']
selected_regions['theta'] = ['LPO', 'LC', 'RPO']
selected_regions['alpha1'] = ['LPO', 'RPO']
selected_regions['alpha2'] = ['LC', 'RPO']

### 7. Network Metrics for selected regions for selected bands


Boxplot helps in reading median, interquartile range and outliers
Box : middle 50% of all data lies (Interquartile range)
Lower end: 1st quartile
Upper end: 3rd quartile
Solid line: Median
Dashed line: Mean
T shaped whiskers: Last point 1.5 times the interquartile range (max and min without outliers)
Points: Further out are outliers

In [31]:
group_measures = ['Lw', 'NBC', 'Eglo', 'CC', 'Eloc']

In [32]:
# def calculate_avergae_components(G):
#     connected_components = list(nx.connected_components(G))
#     component_avg_lengths = []
#     component_nbc_values = []
#     component_eglo_values = []
#     component_cc_values = []
#     component_eloc_values = []

#     for component in connected_components:
#         subgraph = G.subgraph(component)
#         component_avg_lengths.append(nx.average_shortest_path_length(subgraph))
#         component_nbc_values.append(nx.betweenness_centrality(subgraph))
#         component_eglo_values.append(nx.global_efficiency(subgraph))
#         component_cc_values.append(nx.clustering(subgraph))
#         component_eloc_values.append(nx.local_efficiency(subgraph))

#     merged_nbc_values = {}
#     for dnbc in component_nbc_values:
#         merged_nbc_values.update(dnbc)
#     merged_nbc_values = dict(sorted(merged_nbc_values.items(), key=lambda item: item[0]))
#     merged_cc_values = {}
#     for dcc in component_cc_values:
#         merged_cc_values.update(dcc)
#     merged_cc_values = dict(sorted(merged_cc_values.items(), key=lambda item: item[0]))

#     overall_avg_length = sum(component_avg_lengths) / len(component_avg_lengths)
#     overall_eglo_values = sum(component_eglo_values) / len(component_eglo_values)
#     overall_eloc_values = sum(component_eloc_values) / len(component_eloc_values)

#     return [overall_avg_length, merged_nbc_values, overall_eglo_values, merged_cc_values, overall_eloc_values]

In [38]:
# Integration metrics - Lavg, Eglo 
# Segregation metrics - CC, Eloc, Nbc
import seaborn as sns
for i in range(len(freq_bands)):
    selected_region = selected_regions[mapping[i]]

    if selected_region == []:
        continue

    # con_MDD = connectivity_matrix(epochs_MDD, i)
    # con_control = connectivity_matrix(epochs_control, i)
    G_MDD = nx.from_numpy_array(binarized_matrix[f'MDD-{mapping[i]}'])
    G_Control = nx.from_numpy_array(binarized_matrix[f'Control-{mapping[i]}'])

    for region in selected_region:
        channels_list = regionvschannel[region]
        G_sub = G_MDD.subgraph(return_index(channels_list, raw_MDD))
        MDD_list = calculate_avergae_components(G_sub)
        G_sub = G_Control.subgraph(return_index(channels_list, raw_control))
        control_list = calculate_avergae_components(G_sub)

        print(MDD_list, "fdhgjgdfjd", control_list)

        # CHECK HERE if keys in MDD_list[1] matches with keys in control_list[1]
        # and keys in MDD_list[3] matches with keys in control_list[3]
        
        values_MDD = []
        values_control = []
        group_labels_MDD = []
        group_labels_control = [] 

        for _ in range(5):
            print("********", MDD_list)
            if len(MDD_list[_]):
                if type(MDD_list[_][0]) == type(dict()):
                    x = []
                    for __ in range(len(MDD_list[_])):
                        for k,v in MDD_list[_][__].items():
                            x.append(v)
                    values_MDD.append(x)
                else:
                    values_MDD.append(MDD_list[_])
            else:
                values_MDD.append([])
            if (control_list[_]):
                if type(control_list[_][0]) == type(dict()):
                    y = []
                    for __ in range(len(control_list[_])):
                        for k,v in control_list[_][__].items():
                            y.append(v)
                    values_control.append(y)
                else:
                    values_control.append(control_list[_])
            else:
                values_control.append([])
            group_labels_MDD.append(f'MDD-{group_measures[_]}')
            group_labels_control.append(f'Control-{group_measures[_]}')
            
        values_all = values_MDD + values_control
        group_labels = group_labels_MDD + group_labels_control

        print("values all", values_all)
        print("group labels", group_labels)

        plt.figure(figsize=(12, 8))
        plt.boxplot(values_all, labels=group_labels, vert=True)
        plt.title(f'Boxplot of Network Metrics for MDD and Control Groups in {mapping[i]} band in {region} region')
        plt.xlabel('Network Metrics')
        plt.ylabel('Values')
        plt.show()

[0.0, {11: 0.0, 26: 0.0, 27: 0.0}, 0.0, 0.0, 0.0] fdhgjgdfjd [0.0, {11: 0.0, 26: 0.0, 27: 0.0}, 0.0, 0.0, 0.0]
******** [0.0, {11: 0.0, 26: 0.0, 27: 0.0}, 0.0, 0.0, 0.0]


TypeError: object of type 'float' has no len()

8. Mark all regions in brain along with Netowrk metrics which are significant

[]


9. Find relationship between "these" Network Metrics and PHQ-9 scores 

10. For further evaluation: RF based on ensemble learning, SVM, KNN, ANN with 10-fold cross validation 